// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrbitalGuardian.Infrastructure.Persistence;

#nullable disable

namespace OrbitalGuardian.Infrastructure.Migrations
{
    [DbContext(typeof(OrbitalGuardianDbContext))]
    partial class OrbitalGuardianDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.Conjunctions.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConjunctionEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConjunctionEventId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.Conjunctions.ConjunctionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PredictedTcaUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrimaryObjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SecondaryObjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConjunctionEvents");
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Agency");

                    b.Property<int>("CrewCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CrewCapacity");

                    b.Property<double>("EstimatedSizeM")
                        .HasColumnType("REAL")
                        .HasColumnName("EstimatedSizeM");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("MassKg")
                        .HasColumnType("REAL")
                        .HasColumnName("MassKg");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("MissionType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoradId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Operator");

                    b.Property<string>("OriginObject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("OriginObject");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SpaceObjects");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.TelemetryReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpaceObjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpaceObjectId");

                    b.ToTable("TelemetryReadings");
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.Satellite", b =>
                {
                    b.HasBaseType("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceObject");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceDebris", b =>
                {
                    b.HasBaseType("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceObject");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceStation", b =>
                {
                    b.HasBaseType("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceObject");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.Conjunctions.Alert", b =>
                {
                    b.HasOne("OrbitalGuardian.Domain.Aggregates.Conjunctions.ConjunctionEvent", null)
                        .WithMany("Alerts")
                        .HasForeignKey("ConjunctionEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.Conjunctions.ConjunctionEvent", b =>
                {
                    b.OwnsOne("OrbitalGuardian.Domain.ValueObjects.CollisionProbability", "CollisionProbability", b1 =>
                        {
                            b1.Property<Guid>("ConjunctionEventId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL")
                                .HasColumnName("CollisionProbabilityValue");

                            b1.HasKey("ConjunctionEventId");

                            b1.ToTable("ConjunctionEvents");

                            b1.WithOwner()
                                .HasForeignKey("ConjunctionEventId");
                        });

                    b.OwnsOne("OrbitalGuardian.Domain.ValueObjects.MissDistance", "MissDistance", b1 =>
                        {
                            b1.Property<Guid>("ConjunctionEventId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("TimeToClosestApproachSeconds")
                                .HasColumnType("REAL")
                                .HasColumnName("TcaSeconds");

                            b1.Property<double>("ValueKm")
                                .HasColumnType("REAL")
                                .HasColumnName("MissDistanceKm");

                            b1.HasKey("ConjunctionEventId");

                            b1.ToTable("ConjunctionEvents");

                            b1.WithOwner()
                                .HasForeignKey("ConjunctionEventId");
                        });

                    b.Navigation("CollisionProbability")
                        .IsRequired();

                    b.Navigation("MissDistance")
                        .IsRequired();
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceObject", b =>
                {
                    b.OwnsOne("OrbitalGuardian.Domain.ValueObjects.OrbitalElements", "OrbitalElements", b1 =>
                        {
                            b1.Property<Guid>("SpaceObjectId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("ArgumentOfPerigee")
                                .HasColumnType("REAL")
                                .HasColumnName("OE_ArgumentOfPerigee");

                            b1.Property<double>("Eccentricity")
                                .HasColumnType("REAL")
                                .HasColumnName("OE_Eccentricity");

                            b1.Property<double>("Inclination")
                                .HasColumnType("REAL")
                                .HasColumnName("OE_Inclination");

                            b1.Property<double>("MeanAnomaly")
                                .HasColumnType("REAL")
                                .HasColumnName("OE_MeanAnomaly");

                            b1.Property<double>("MeanMotion")
                                .HasColumnType("REAL")
                                .HasColumnName("OE_MeanMotion");

                            b1.Property<double>("RightAscension")
                                .HasColumnType("REAL")
                                .HasColumnName("OE_RightAscension");

                            b1.HasKey("SpaceObjectId");

                            b1.ToTable("SpaceObjects");

                            b1.WithOwner()
                                .HasForeignKey("SpaceObjectId");
                        });

                    b.Navigation("OrbitalElements")
                        .IsRequired();
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.TelemetryReading", b =>
                {
                    b.HasOne("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceObject", null)
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("SpaceObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OrbitalGuardian.Domain.ValueObjects.StateVector", "StateVector", b1 =>
                        {
                            b1.Property<Guid>("TelemetryReadingId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("PositionalUncertaintyKm")
                                .HasColumnType("REAL")
                                .HasColumnName("SV_UncertaintyKm");

                            b1.HasKey("TelemetryReadingId");

                            b1.ToTable("TelemetryReadings");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryReadingId");

                            b1.OwnsOne("OrbitalGuardian.Domain.ValueObjects.Coordinates", "Position", b2 =>
                                {
                                    b2.Property<Guid>("StateVectorTelemetryReadingId")
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("X")
                                        .HasColumnType("REAL")
                                        .HasColumnName("SV_Pos_X");

                                    b2.Property<double>("Y")
                                        .HasColumnType("REAL")
                                        .HasColumnName("SV_Pos_Y");

                                    b2.Property<double>("Z")
                                        .HasColumnType("REAL")
                                        .HasColumnName("SV_Pos_Z");

                                    b2.HasKey("StateVectorTelemetryReadingId");

                                    b2.ToTable("TelemetryReadings");

                                    b2.WithOwner()
                                        .HasForeignKey("StateVectorTelemetryReadingId");
                                });

                            b1.OwnsOne("OrbitalGuardian.Domain.ValueObjects.Coordinates", "Velocity", b2 =>
                                {
                                    b2.Property<Guid>("StateVectorTelemetryReadingId")
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("X")
                                        .HasColumnType("REAL")
                                        .HasColumnName("SV_Vel_X");

                                    b2.Property<double>("Y")
                                        .HasColumnType("REAL")
                                        .HasColumnName("SV_Vel_Y");

                                    b2.Property<double>("Z")
                                        .HasColumnType("REAL")
                                        .HasColumnName("SV_Vel_Z");

                                    b2.HasKey("StateVectorTelemetryReadingId");

                                    b2.ToTable("TelemetryReadings");

                                    b2.WithOwner()
                                        .HasForeignKey("StateVectorTelemetryReadingId");
                                });

                            b1.Navigation("Position")
                                .IsRequired();

                            b1.Navigation("Velocity")
                                .IsRequired();
                        });

                    b.Navigation("StateVector")
                        .IsRequired();
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.Conjunctions.ConjunctionEvent", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("OrbitalGuardian.Domain.Aggregates.SpaceObjects.SpaceObject", b =>
                {
                    b.Navigation("TelemetryReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
